apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: finance-batch-hpa
  namespace: finance
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: finance-batch
  targetCPUUtilizationPercentage: 70
