apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: finance-batch
  namespace: finance
  labels:
    app: finance-batch
    project: finance
    release: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      project: finance
      app: finance-batch
      release: {{ .Release.Name }}
  template:
    metadata:
      namespace: finance
      labels:
        project: finance
        app: finance-batch
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: finance-batch
        image: nginx:{{ .Values.tag }}
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        livenessProbe:
          initialDelaySeconds: 20
          failureThreshold: 5
          periodSeconds: 10
          httpGet:
            path: /
            port: http
        readinessProbe:
          initialDelaySeconds: 10
          failureThreshold: 3
          httpGet:
            path: /
            port: http
  strategy:
    blueGreen:
      activeService: finance-batch
      previewService: finance-batch-preview
      autoPromotionEnabled: false
