apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: finance-batch
  namespace: finance
  labels:
    app: finance-batch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-batch
  template:
    metadata:
      namespace: finance
      labels:
        app: finance-batch
    spec:
      containers:
      - name: finance-batch
        image: nginx:{{ .Values.tag }}
        ports:
          - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 10
          failureThreshold: 3
          httpGet:
            path: /
            port: http
  strategy:
    blueGreen:
      activeService: finance-batch
      previewService: finance-batch-preview
      autoPromotionEnabled: true
