---
apiVersion: v1
kind: Service
metadata:
  name: finance-batch
  namespace: finance
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: finance-batch
    project: finance-batch
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: finance-batch-preview
  namespace: finance
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: finance-batch
    project: finance-batch
    release: {{ .Release.Name }}
