apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: demo-finance-api-aws-secrets-manager 
  namespace: demo
spec:
  backendType: secretsManager
  data:
  - key: kubernetes/external-secret/finance
    name: testkey
    property: testval