---
apiVersion: v1
kind: Service
metadata:
  name: demo-finance-api
  namespace: demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: demo-finance-api
    project: demo-finance
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: demo-finance-api-preview
  namespace: demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: demo-finance-api
    release: {{ .Release.Name }}